name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |

        docker buildx create --use
        docker buildx build -t ayushsharma4102267/myplugin:${{ github.run_number }} --platform linux/amd64,linux/arm64 -o type=registry,image=docker.io/ayushsharma4102267/myplugin:${{ github.run_number }} .
        echo "dckr_pat_mIBDmcs_1L_TPM43V2YvwHwO8EI" | docker login -u ayushsharma4102267 --password-stdin
        docker push docker.io/ayushsharma4102267/myplugin:${{ github.run_number }}
